//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class InputEntity {

    public Entitas.Data.KeyDownComponent keyDown { get { return (Entitas.Data.KeyDownComponent)GetComponent(InputComponentsLookup.KeyDown); } }
    public bool hasKeyDown { get { return HasComponent(InputComponentsLookup.KeyDown); } }

    public void AddKeyDown(UnityEngine.KeyCode newValue) {
        var index = InputComponentsLookup.KeyDown;
        var component = CreateComponent<Entitas.Data.KeyDownComponent>(index);
        component.Value = newValue;
        AddComponent(index, component);
    }

    public void ReplaceKeyDown(UnityEngine.KeyCode newValue) {
        var index = InputComponentsLookup.KeyDown;
        var component = CreateComponent<Entitas.Data.KeyDownComponent>(index);
        component.Value = newValue;
        ReplaceComponent(index, component);
    }

    public void RemoveKeyDown() {
        RemoveComponent(InputComponentsLookup.KeyDown);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class InputMatcher {

    static Entitas.IMatcher<InputEntity> _matcherKeyDown;

    public static Entitas.IMatcher<InputEntity> KeyDown {
        get {
            if (_matcherKeyDown == null) {
                var matcher = (Entitas.Matcher<InputEntity>)Entitas.Matcher<InputEntity>.AllOf(InputComponentsLookup.KeyDown);
                matcher.componentNames = InputComponentsLookup.componentNames;
                _matcherKeyDown = matcher;
            }

            return _matcherKeyDown;
        }
    }
}
