//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ContextMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class ChunkMatcher {

    public static Entitas.IAllOfMatcher<ChunkEntity> AllOf(params int[] indices) {
        return Entitas.Matcher<ChunkEntity>.AllOf(indices);
    }

    public static Entitas.IAllOfMatcher<ChunkEntity> AllOf(params Entitas.IMatcher<ChunkEntity>[] matchers) {
          return Entitas.Matcher<ChunkEntity>.AllOf(matchers);
    }

    public static Entitas.IAnyOfMatcher<ChunkEntity> AnyOf(params int[] indices) {
          return Entitas.Matcher<ChunkEntity>.AnyOf(indices);
    }

    public static Entitas.IAnyOfMatcher<ChunkEntity> AnyOf(params Entitas.IMatcher<ChunkEntity>[] matchers) {
          return Entitas.Matcher<ChunkEntity>.AnyOf(matchers);
    }
}
