// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

public class CharacterAgent : behaviac.Agent
///<<< BEGIN WRITING YOUR CODE CharacterAgent
///<<< END WRITING YOUR CODE
{
	public bool CanUseSkill()
	{
///<<< BEGIN WRITING YOUR CODE CanUseSkill
        return null == GetOwner().skill.Instance;
///<<< END WRITING YOUR CODE
	}

	public void UseSkill(int SkillId)
	{
///<<< BEGIN WRITING YOUR CODE UseSkill
        GameEntity self = GetOwner();
        UnityClient.SkillSystem.Instance.StartSkill(self, self, SkillId);
///<<< END WRITING YOUR CODE
	}

///<<< BEGIN WRITING YOUR CODE CLASS_PART

        public void Init(uint id)
    {
        m_EntityId = id;
    }
    private GameEntity GetOwner()
    {
        return Contexts.sharedInstance.game.GetEntityWithId(m_EntityId);
    }
    private uint m_EntityId;

///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

