//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentLookupGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class GameStateComponentsLookup {

    public const int LevelCleanUp = 0;
    public const int Level = 1;
    public const int LevelLoaded = 2;
    public const int NextLevel = 3;

    public const int TotalComponents = 4;

    public static readonly string[] componentNames = {
        "LevelCleanUp",
        "Level",
        "LevelLoaded",
        "NextLevel"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(Entitas.Data.LevelCleanUpComponent),
        typeof(Entitas.Data.LevelComponent),
        typeof(Entitas.Data.LevelLoadedComponent),
        typeof(Entitas.Data.NextLevelComponent)
    };
}
