//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentLookupGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class GameStateComponentsLookup {

    public const int CurSceneId = 0;
    public const int LoadingProgress = 1;
    public const int NextSceneId = 2;
    public const int SceneLoadFinished = 3;
    public const int TargetSceneId = 4;

    public const int TotalComponents = 5;

    public static readonly string[] componentNames = {
        "CurSceneId",
        "LoadingProgress",
        "NextSceneId",
        "SceneLoadFinished",
        "TargetSceneId"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(Entitas.Data.CurSceneIdComponent),
        typeof(Entitas.Data.LoadingProgressComponent),
        typeof(Entitas.Data.NextSceneIdComponent),
        typeof(Entitas.Data.SceneLoadFinishedComponent),
        typeof(Entitas.Data.TargetSceneIdComponent)
    };
}
