//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentContextApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameStateContext {

    public GameStateEntity levelEntity { get { return GetGroup(GameStateMatcher.Level).GetSingleEntity(); } }
    public Entitas.Data.LevelComponent level { get { return levelEntity.level; } }
    public bool hasLevel { get { return levelEntity != null; } }

    public GameStateEntity SetLevel(int newValue) {
        if (hasLevel) {
            throw new Entitas.EntitasException("Could not set Level!\n" + this + " already has an entity with Entitas.Data.LevelComponent!",
                "You should check if the context already has a levelEntity before setting it or use context.ReplaceLevel().");
        }
        var entity = CreateEntity();
        entity.AddLevel(newValue);
        return entity;
    }

    public void ReplaceLevel(int newValue) {
        var entity = levelEntity;
        if (entity == null) {
            entity = SetLevel(newValue);
        } else {
            entity.ReplaceLevel(newValue);
        }
    }

    public void RemoveLevel() {
        levelEntity.Destroy();
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentContextApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameStateContext {

    public GameStateEntity nextLevelEntity { get { return GetGroup(GameStateMatcher.NextLevel).GetSingleEntity(); } }
    public Entitas.Data.NextLevelComponent nextLevel { get { return nextLevelEntity.nextLevel; } }
    public bool hasNextLevel { get { return nextLevelEntity != null; } }

    public GameStateEntity SetNextLevel(int newValue) {
        if (hasNextLevel) {
            throw new Entitas.EntitasException("Could not set NextLevel!\n" + this + " already has an entity with Entitas.Data.NextLevelComponent!",
                "You should check if the context already has a nextLevelEntity before setting it or use context.ReplaceNextLevel().");
        }
        var entity = CreateEntity();
        entity.AddNextLevel(newValue);
        return entity;
    }

    public void ReplaceNextLevel(int newValue) {
        var entity = nextLevelEntity;
        if (entity == null) {
            entity = SetNextLevel(newValue);
        } else {
            entity.ReplaceNextLevel(newValue);
        }
    }

    public void RemoveNextLevel() {
        nextLevelEntity.Destroy();
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentContextApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameStateContext {

    public GameStateEntity levelCleanUpEntity { get { return GetGroup(GameStateMatcher.LevelCleanUp).GetSingleEntity(); } }

    public bool isLevelCleanUp {
        get { return levelCleanUpEntity != null; }
        set {
            var entity = levelCleanUpEntity;
            if (value != (entity != null)) {
                if (value) {
                    CreateEntity().isLevelCleanUp = true;
                } else {
                    entity.Destroy();
                }
            }
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentContextApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameStateContext {

    public GameStateEntity levelLoadedEntity { get { return GetGroup(GameStateMatcher.LevelLoaded).GetSingleEntity(); } }

    public bool isLevelLoaded {
        get { return levelLoadedEntity != null; }
        set {
            var entity = levelLoadedEntity;
            if (value != (entity != null)) {
                if (value) {
                    CreateEntity().isLevelLoaded = true;
                } else {
                    entity.Destroy();
                }
            }
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameStateEntity {

    public Entitas.Data.LevelComponent level { get { return (Entitas.Data.LevelComponent)GetComponent(GameStateComponentsLookup.Level); } }
    public bool hasLevel { get { return HasComponent(GameStateComponentsLookup.Level); } }

    public void AddLevel(int newValue) {
        var index = GameStateComponentsLookup.Level;
        var component = CreateComponent<Entitas.Data.LevelComponent>(index);
        component.Value = newValue;
        AddComponent(index, component);
    }

    public void ReplaceLevel(int newValue) {
        var index = GameStateComponentsLookup.Level;
        var component = CreateComponent<Entitas.Data.LevelComponent>(index);
        component.Value = newValue;
        ReplaceComponent(index, component);
    }

    public void RemoveLevel() {
        RemoveComponent(GameStateComponentsLookup.Level);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameStateEntity {

    public Entitas.Data.NextLevelComponent nextLevel { get { return (Entitas.Data.NextLevelComponent)GetComponent(GameStateComponentsLookup.NextLevel); } }
    public bool hasNextLevel { get { return HasComponent(GameStateComponentsLookup.NextLevel); } }

    public void AddNextLevel(int newValue) {
        var index = GameStateComponentsLookup.NextLevel;
        var component = CreateComponent<Entitas.Data.NextLevelComponent>(index);
        component.Value = newValue;
        AddComponent(index, component);
    }

    public void ReplaceNextLevel(int newValue) {
        var index = GameStateComponentsLookup.NextLevel;
        var component = CreateComponent<Entitas.Data.NextLevelComponent>(index);
        component.Value = newValue;
        ReplaceComponent(index, component);
    }

    public void RemoveNextLevel() {
        RemoveComponent(GameStateComponentsLookup.NextLevel);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameStateEntity {

    static readonly Entitas.Data.LevelCleanUpComponent levelCleanUpComponent = new Entitas.Data.LevelCleanUpComponent();

    public bool isLevelCleanUp {
        get { return HasComponent(GameStateComponentsLookup.LevelCleanUp); }
        set {
            if (value != isLevelCleanUp) {
                var index = GameStateComponentsLookup.LevelCleanUp;
                if (value) {
                    var componentPool = GetComponentPool(index);
                    var component = componentPool.Count > 0
                            ? componentPool.Pop()
                            : levelCleanUpComponent;

                    AddComponent(index, component);
                } else {
                    RemoveComponent(index);
                }
            }
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameStateEntity {

    static readonly Entitas.Data.LevelLoadedComponent levelLoadedComponent = new Entitas.Data.LevelLoadedComponent();

    public bool isLevelLoaded {
        get { return HasComponent(GameStateComponentsLookup.LevelLoaded); }
        set {
            if (value != isLevelLoaded) {
                var index = GameStateComponentsLookup.LevelLoaded;
                if (value) {
                    var componentPool = GetComponentPool(index);
                    var component = componentPool.Count > 0
                            ? componentPool.Pop()
                            : levelLoadedComponent;

                    AddComponent(index, component);
                } else {
                    RemoveComponent(index);
                }
            }
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameStateMatcher {

    static Entitas.IMatcher<GameStateEntity> _matcherLevel;

    public static Entitas.IMatcher<GameStateEntity> Level {
        get {
            if (_matcherLevel == null) {
                var matcher = (Entitas.Matcher<GameStateEntity>)Entitas.Matcher<GameStateEntity>.AllOf(GameStateComponentsLookup.Level);
                matcher.componentNames = GameStateComponentsLookup.componentNames;
                _matcherLevel = matcher;
            }

            return _matcherLevel;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameStateMatcher {

    static Entitas.IMatcher<GameStateEntity> _matcherNextLevel;

    public static Entitas.IMatcher<GameStateEntity> NextLevel {
        get {
            if (_matcherNextLevel == null) {
                var matcher = (Entitas.Matcher<GameStateEntity>)Entitas.Matcher<GameStateEntity>.AllOf(GameStateComponentsLookup.NextLevel);
                matcher.componentNames = GameStateComponentsLookup.componentNames;
                _matcherNextLevel = matcher;
            }

            return _matcherNextLevel;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameStateMatcher {

    static Entitas.IMatcher<GameStateEntity> _matcherLevelCleanUp;

    public static Entitas.IMatcher<GameStateEntity> LevelCleanUp {
        get {
            if (_matcherLevelCleanUp == null) {
                var matcher = (Entitas.Matcher<GameStateEntity>)Entitas.Matcher<GameStateEntity>.AllOf(GameStateComponentsLookup.LevelCleanUp);
                matcher.componentNames = GameStateComponentsLookup.componentNames;
                _matcherLevelCleanUp = matcher;
            }

            return _matcherLevelCleanUp;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameStateMatcher {

    static Entitas.IMatcher<GameStateEntity> _matcherLevelLoaded;

    public static Entitas.IMatcher<GameStateEntity> LevelLoaded {
        get {
            if (_matcherLevelLoaded == null) {
                var matcher = (Entitas.Matcher<GameStateEntity>)Entitas.Matcher<GameStateEntity>.AllOf(GameStateComponentsLookup.LevelLoaded);
                matcher.componentNames = GameStateComponentsLookup.componentNames;
                _matcherLevelLoaded = matcher;
            }

            return _matcherLevelLoaded;
        }
    }
}
