//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentLookupGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class GameComponentsLookup {

    public const int AI = 0;
    public const int Animation = 1;
    public const int Attr = 2;
    public const int Born = 3;
    public const int BuffAttrChanged = 4;
    public const int Buff = 5;
    public const int Camp = 6;
    public const int Chunk = 7;
    public const int ChunkDoor = 8;
    public const int ChunkTrigger = 9;
    public const int Collision = 10;
    public const int Dead = 11;
    public const int Destory = 12;
    public const int Hp = 13;
    public const int Id = 14;
    public const int MainPlayer = 15;
    public const int Movement = 16;
    public const int Physics = 17;
    public const int Position = 18;
    public const int Resource = 19;
    public const int Rotation = 20;
    public const int Scene = 21;
    public const int Skill = 22;
    public const int TimeInfo = 23;
    public const int View = 24;

    public const int TotalComponents = 25;

    public static readonly string[] componentNames = {
        "AI",
        "Animation",
        "Attr",
        "Born",
        "BuffAttrChanged",
        "Buff",
        "Camp",
        "Chunk",
        "ChunkDoor",
        "ChunkTrigger",
        "Collision",
        "Dead",
        "Destory",
        "Hp",
        "Id",
        "MainPlayer",
        "Movement",
        "Physics",
        "Position",
        "Resource",
        "Rotation",
        "Scene",
        "Skill",
        "TimeInfo",
        "View"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(Entitas.Data.AIComponent),
        typeof(Entitas.Data.AnimationComponent),
        typeof(Entitas.Data.AttrComponent),
        typeof(Entitas.Data.BornComponent),
        typeof(Entitas.Data.BuffAttrChangedComponent),
        typeof(Entitas.Data.BuffComponent),
        typeof(Entitas.Data.CampComponent),
        typeof(Entitas.Data.ChunkComponent),
        typeof(Entitas.Data.ChunkDoorComponent),
        typeof(Entitas.Data.ChunkTriggerComponent),
        typeof(Entitas.Data.CollisionComponent),
        typeof(Entitas.Data.DeadComponent),
        typeof(Entitas.Data.DestoryComponent),
        typeof(Entitas.Data.HpComponent),
        typeof(Entitas.Data.IdComponent),
        typeof(Entitas.Data.MainPlayerComponent),
        typeof(Entitas.Data.MovementComponent),
        typeof(Entitas.Data.PhysicsComponent),
        typeof(Entitas.Data.PositionComponent),
        typeof(Entitas.Data.ResourceComponent),
        typeof(Entitas.Data.RotationComponent),
        typeof(Entitas.Data.SceneComponent),
        typeof(Entitas.Data.SkillComponent),
        typeof(Entitas.Data.TimeInfoComponent),
        typeof(Entitas.Data.ViewComponent)
    };
}
