//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentContextGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameContext {

    public GameEntity mainPlayerEntity { get { return GetGroup(GameMatcher.MainPlayer).GetSingleEntity(); } }

    public bool isMainPlayer {
        get { return mainPlayerEntity != null; }
        set {
            var entity = mainPlayerEntity;
            if (value != (entity != null)) {
                if (value) {
                    CreateEntity().isMainPlayer = true;
                } else {
                    entity.Destroy();
                }
            }
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentContextGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameContext {

    public GameEntity timeInfoEntity { get { return GetGroup(GameMatcher.TimeInfo).GetSingleEntity(); } }
    public Entitas.Data.TimeInfoComponent timeInfo { get { return timeInfoEntity.timeInfo; } }
    public bool hasTimeInfo { get { return timeInfoEntity != null; } }

    public GameEntity SetTimeInfo(float newTime, float newDeltaTime) {
        if (hasTimeInfo) {
            throw new Entitas.EntitasException("Could not set TimeInfo!\n" + this + " already has an entity with Entitas.Data.TimeInfoComponent!",
                "You should check if the context already has a timeInfoEntity before setting it or use context.ReplaceTimeInfo().");
        }
        var entity = CreateEntity();
        entity.AddTimeInfo(newTime, newDeltaTime);
        return entity;
    }

    public void ReplaceTimeInfo(float newTime, float newDeltaTime) {
        var entity = timeInfoEntity;
        if (entity == null) {
            entity = SetTimeInfo(newTime, newDeltaTime);
        } else {
            entity.ReplaceTimeInfo(newTime, newDeltaTime);
        }
    }

    public void RemoveTimeInfo() {
        timeInfoEntity.Destroy();
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentContextGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameContext {

    public GameEntity sceneEntity { get { return GetGroup(GameMatcher.Scene).GetSingleEntity(); } }
    public Entitas.Data.SceneComponent scene { get { return sceneEntity.scene; } }
    public bool hasScene { get { return sceneEntity != null; } }

    public GameEntity SetScene(Entitas.Data.SceneConfig newConfig, Entitas.Data.SceneInstanceInfo newScriptInstance) {
        if (hasScene) {
            throw new Entitas.EntitasException("Could not set Scene!\n" + this + " already has an entity with Entitas.Data.SceneComponent!",
                "You should check if the context already has a sceneEntity before setting it or use context.ReplaceScene().");
        }
        var entity = CreateEntity();
        entity.AddScene(newConfig, newScriptInstance);
        return entity;
    }

    public void ReplaceScene(Entitas.Data.SceneConfig newConfig, Entitas.Data.SceneInstanceInfo newScriptInstance) {
        var entity = sceneEntity;
        if (entity == null) {
            entity = SetScene(newConfig, newScriptInstance);
        } else {
            entity.ReplaceScene(newConfig, newScriptInstance);
        }
    }

    public void RemoveScene() {
        sceneEntity.Destroy();
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.MovementComponent movement { get { return (Entitas.Data.MovementComponent)GetComponent(GameComponentsLookup.Movement); } }
    public bool hasMovement { get { return HasComponent(GameComponentsLookup.Movement); } }

    public void AddMovement(Util.Vector3 newVelocity) {
        var index = GameComponentsLookup.Movement;
        var component = CreateComponent<Entitas.Data.MovementComponent>(index);
        component.Velocity = newVelocity;
        AddComponent(index, component);
    }

    public void ReplaceMovement(Util.Vector3 newVelocity) {
        var index = GameComponentsLookup.Movement;
        var component = CreateComponent<Entitas.Data.MovementComponent>(index);
        component.Velocity = newVelocity;
        ReplaceComponent(index, component);
    }

    public void RemoveMovement() {
        RemoveComponent(GameComponentsLookup.Movement);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.PositionComponent position { get { return (Entitas.Data.PositionComponent)GetComponent(GameComponentsLookup.Position); } }
    public bool hasPosition { get { return HasComponent(GameComponentsLookup.Position); } }

    public void AddPosition(Util.Vector3 newValue) {
        var index = GameComponentsLookup.Position;
        var component = CreateComponent<Entitas.Data.PositionComponent>(index);
        component.Value = newValue;
        AddComponent(index, component);
    }

    public void ReplacePosition(Util.Vector3 newValue) {
        var index = GameComponentsLookup.Position;
        var component = CreateComponent<Entitas.Data.PositionComponent>(index);
        component.Value = newValue;
        ReplaceComponent(index, component);
    }

    public void RemovePosition() {
        RemoveComponent(GameComponentsLookup.Position);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.RotationComponent rotation { get { return (Entitas.Data.RotationComponent)GetComponent(GameComponentsLookup.Rotation); } }
    public bool hasRotation { get { return HasComponent(GameComponentsLookup.Rotation); } }

    public void AddRotation(float newRotateDir) {
        var index = GameComponentsLookup.Rotation;
        var component = CreateComponent<Entitas.Data.RotationComponent>(index);
        component.RotateDir = newRotateDir;
        AddComponent(index, component);
    }

    public void ReplaceRotation(float newRotateDir) {
        var index = GameComponentsLookup.Rotation;
        var component = CreateComponent<Entitas.Data.RotationComponent>(index);
        component.RotateDir = newRotateDir;
        ReplaceComponent(index, component);
    }

    public void RemoveRotation() {
        RemoveComponent(GameComponentsLookup.Rotation);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.AnimationComponent animation { get { return (Entitas.Data.AnimationComponent)GetComponent(GameComponentsLookup.Animation); } }
    public bool hasAnimation { get { return HasComponent(GameComponentsLookup.Animation); } }

    public void AddAnimation(int newActionId, string newPrefix) {
        var index = GameComponentsLookup.Animation;
        var component = CreateComponent<Entitas.Data.AnimationComponent>(index);
        component.ActionId = newActionId;
        component.Prefix = newPrefix;
        AddComponent(index, component);
    }

    public void ReplaceAnimation(int newActionId, string newPrefix) {
        var index = GameComponentsLookup.Animation;
        var component = CreateComponent<Entitas.Data.AnimationComponent>(index);
        component.ActionId = newActionId;
        component.Prefix = newPrefix;
        ReplaceComponent(index, component);
    }

    public void RemoveAnimation() {
        RemoveComponent(GameComponentsLookup.Animation);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    static readonly Entitas.Data.DisableMoveControlComponent disableMoveControlComponent = new Entitas.Data.DisableMoveControlComponent();

    public bool isDisableMoveControl {
        get { return HasComponent(GameComponentsLookup.DisableMoveControl); }
        set {
            if (value != isDisableMoveControl) {
                if (value) {
                    AddComponent(GameComponentsLookup.DisableMoveControl, disableMoveControlComponent);
                } else {
                    RemoveComponent(GameComponentsLookup.DisableMoveControl);
                }
            }
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    static readonly Entitas.Data.DisableRotationControlComponent disableRotationControlComponent = new Entitas.Data.DisableRotationControlComponent();

    public bool isDisableRotationControl {
        get { return HasComponent(GameComponentsLookup.DisableRotationControl); }
        set {
            if (value != isDisableRotationControl) {
                if (value) {
                    AddComponent(GameComponentsLookup.DisableRotationControl, disableRotationControlComponent);
                } else {
                    RemoveComponent(GameComponentsLookup.DisableRotationControl);
                }
            }
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.IdComponent id { get { return (Entitas.Data.IdComponent)GetComponent(GameComponentsLookup.Id); } }
    public bool hasId { get { return HasComponent(GameComponentsLookup.Id); } }

    public void AddId(uint newValue) {
        var index = GameComponentsLookup.Id;
        var component = CreateComponent<Entitas.Data.IdComponent>(index);
        component.value = newValue;
        AddComponent(index, component);
    }

    public void ReplaceId(uint newValue) {
        var index = GameComponentsLookup.Id;
        var component = CreateComponent<Entitas.Data.IdComponent>(index);
        component.value = newValue;
        ReplaceComponent(index, component);
    }

    public void RemoveId() {
        RemoveComponent(GameComponentsLookup.Id);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.ResourceComponent resource { get { return (Entitas.Data.ResourceComponent)GetComponent(GameComponentsLookup.Resource); } }
    public bool hasResource { get { return HasComponent(GameComponentsLookup.Resource); } }

    public void AddResource(uint newValue) {
        var index = GameComponentsLookup.Resource;
        var component = CreateComponent<Entitas.Data.ResourceComponent>(index);
        component.Value = newValue;
        AddComponent(index, component);
    }

    public void ReplaceResource(uint newValue) {
        var index = GameComponentsLookup.Resource;
        var component = CreateComponent<Entitas.Data.ResourceComponent>(index);
        component.Value = newValue;
        ReplaceComponent(index, component);
    }

    public void RemoveResource() {
        RemoveComponent(GameComponentsLookup.Resource);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.AIComponent aI { get { return (Entitas.Data.AIComponent)GetComponent(GameComponentsLookup.AI); } }
    public bool hasAI { get { return HasComponent(GameComponentsLookup.AI); } }

    public void AddAI(behaviac.Agent newAgent) {
        var index = GameComponentsLookup.AI;
        var component = CreateComponent<Entitas.Data.AIComponent>(index);
        component.Agent = newAgent;
        AddComponent(index, component);
    }

    public void ReplaceAI(behaviac.Agent newAgent) {
        var index = GameComponentsLookup.AI;
        var component = CreateComponent<Entitas.Data.AIComponent>(index);
        component.Agent = newAgent;
        ReplaceComponent(index, component);
    }

    public void RemoveAI() {
        RemoveComponent(GameComponentsLookup.AI);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.PhysicsComponent physics { get { return (Entitas.Data.PhysicsComponent)GetComponent(GameComponentsLookup.Physics); } }
    public bool hasPhysics { get { return HasComponent(GameComponentsLookup.Physics); } }

    public void AddPhysics(Entitas.Data.RigidObject newRigid, Util.Vector3 newOffset, Entitas.Data.CollisionDelegate newOnCollision) {
        var index = GameComponentsLookup.Physics;
        var component = CreateComponent<Entitas.Data.PhysicsComponent>(index);
        component.Rigid = newRigid;
        component.Offset = newOffset;
        component.OnCollision = newOnCollision;
        AddComponent(index, component);
    }

    public void ReplacePhysics(Entitas.Data.RigidObject newRigid, Util.Vector3 newOffset, Entitas.Data.CollisionDelegate newOnCollision) {
        var index = GameComponentsLookup.Physics;
        var component = CreateComponent<Entitas.Data.PhysicsComponent>(index);
        component.Rigid = newRigid;
        component.Offset = newOffset;
        component.OnCollision = newOnCollision;
        ReplaceComponent(index, component);
    }

    public void RemovePhysics() {
        RemoveComponent(GameComponentsLookup.Physics);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.CampComponent camp { get { return (Entitas.Data.CampComponent)GetComponent(GameComponentsLookup.Camp); } }
    public bool hasCamp { get { return HasComponent(GameComponentsLookup.Camp); } }

    public void AddCamp(int newValue) {
        var index = GameComponentsLookup.Camp;
        var component = CreateComponent<Entitas.Data.CampComponent>(index);
        component.Value = newValue;
        AddComponent(index, component);
    }

    public void ReplaceCamp(int newValue) {
        var index = GameComponentsLookup.Camp;
        var component = CreateComponent<Entitas.Data.CampComponent>(index);
        component.Value = newValue;
        ReplaceComponent(index, component);
    }

    public void RemoveCamp() {
        RemoveComponent(GameComponentsLookup.Camp);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    static readonly Entitas.Data.DestoryComponent destoryComponent = new Entitas.Data.DestoryComponent();

    public bool isDestory {
        get { return HasComponent(GameComponentsLookup.Destory); }
        set {
            if (value != isDestory) {
                if (value) {
                    AddComponent(GameComponentsLookup.Destory, destoryComponent);
                } else {
                    RemoveComponent(GameComponentsLookup.Destory);
                }
            }
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.AttrComponent attr { get { return (Entitas.Data.AttrComponent)GetComponent(GameComponentsLookup.Attr); } }
    public bool hasAttr { get { return HasComponent(GameComponentsLookup.Attr); } }

    public void AddAttr(int newId, Entitas.Data.AttributeData newValue) {
        var index = GameComponentsLookup.Attr;
        var component = CreateComponent<Entitas.Data.AttrComponent>(index);
        component.Id = newId;
        component.Value = newValue;
        AddComponent(index, component);
    }

    public void ReplaceAttr(int newId, Entitas.Data.AttributeData newValue) {
        var index = GameComponentsLookup.Attr;
        var component = CreateComponent<Entitas.Data.AttrComponent>(index);
        component.Id = newId;
        component.Value = newValue;
        ReplaceComponent(index, component);
    }

    public void RemoveAttr() {
        RemoveComponent(GameComponentsLookup.Attr);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    static readonly Entitas.Data.BuffAttrChangedComponent buffAttrChangedComponent = new Entitas.Data.BuffAttrChangedComponent();

    public bool isBuffAttrChanged {
        get { return HasComponent(GameComponentsLookup.BuffAttrChanged); }
        set {
            if (value != isBuffAttrChanged) {
                if (value) {
                    AddComponent(GameComponentsLookup.BuffAttrChanged, buffAttrChangedComponent);
                } else {
                    RemoveComponent(GameComponentsLookup.BuffAttrChanged);
                }
            }
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.HpComponent hp { get { return (Entitas.Data.HpComponent)GetComponent(GameComponentsLookup.Hp); } }
    public bool hasHp { get { return HasComponent(GameComponentsLookup.Hp); } }

    public void AddHp(float newValue) {
        var index = GameComponentsLookup.Hp;
        var component = CreateComponent<Entitas.Data.HpComponent>(index);
        component.Value = newValue;
        AddComponent(index, component);
    }

    public void ReplaceHp(float newValue) {
        var index = GameComponentsLookup.Hp;
        var component = CreateComponent<Entitas.Data.HpComponent>(index);
        component.Value = newValue;
        ReplaceComponent(index, component);
    }

    public void RemoveHp() {
        RemoveComponent(GameComponentsLookup.Hp);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.DeadComponent dead { get { return (Entitas.Data.DeadComponent)GetComponent(GameComponentsLookup.Dead); } }
    public bool hasDead { get { return HasComponent(GameComponentsLookup.Dead); } }

    public void AddDead(float newDeadTime) {
        var index = GameComponentsLookup.Dead;
        var component = CreateComponent<Entitas.Data.DeadComponent>(index);
        component.DeadTime = newDeadTime;
        AddComponent(index, component);
    }

    public void ReplaceDead(float newDeadTime) {
        var index = GameComponentsLookup.Dead;
        var component = CreateComponent<Entitas.Data.DeadComponent>(index);
        component.DeadTime = newDeadTime;
        ReplaceComponent(index, component);
    }

    public void RemoveDead() {
        RemoveComponent(GameComponentsLookup.Dead);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.BornComponent born { get { return (Entitas.Data.BornComponent)GetComponent(GameComponentsLookup.Born); } }
    public bool hasBorn { get { return HasComponent(GameComponentsLookup.Born); } }

    public void AddBorn(float newBornTime) {
        var index = GameComponentsLookup.Born;
        var component = CreateComponent<Entitas.Data.BornComponent>(index);
        component.BornTime = newBornTime;
        AddComponent(index, component);
    }

    public void ReplaceBorn(float newBornTime) {
        var index = GameComponentsLookup.Born;
        var component = CreateComponent<Entitas.Data.BornComponent>(index);
        component.BornTime = newBornTime;
        ReplaceComponent(index, component);
    }

    public void RemoveBorn() {
        RemoveComponent(GameComponentsLookup.Born);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    static readonly Entitas.Data.MainPlayerComponent mainPlayerComponent = new Entitas.Data.MainPlayerComponent();

    public bool isMainPlayer {
        get { return HasComponent(GameComponentsLookup.MainPlayer); }
        set {
            if (value != isMainPlayer) {
                if (value) {
                    AddComponent(GameComponentsLookup.MainPlayer, mainPlayerComponent);
                } else {
                    RemoveComponent(GameComponentsLookup.MainPlayer);
                }
            }
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.TimeInfoComponent timeInfo { get { return (Entitas.Data.TimeInfoComponent)GetComponent(GameComponentsLookup.TimeInfo); } }
    public bool hasTimeInfo { get { return HasComponent(GameComponentsLookup.TimeInfo); } }

    public void AddTimeInfo(float newTime, float newDeltaTime) {
        var index = GameComponentsLookup.TimeInfo;
        var component = CreateComponent<Entitas.Data.TimeInfoComponent>(index);
        component.Time = newTime;
        component.DeltaTime = newDeltaTime;
        AddComponent(index, component);
    }

    public void ReplaceTimeInfo(float newTime, float newDeltaTime) {
        var index = GameComponentsLookup.TimeInfo;
        var component = CreateComponent<Entitas.Data.TimeInfoComponent>(index);
        component.Time = newTime;
        component.DeltaTime = newDeltaTime;
        ReplaceComponent(index, component);
    }

    public void RemoveTimeInfo() {
        RemoveComponent(GameComponentsLookup.TimeInfo);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.SceneComponent scene { get { return (Entitas.Data.SceneComponent)GetComponent(GameComponentsLookup.Scene); } }
    public bool hasScene { get { return HasComponent(GameComponentsLookup.Scene); } }

    public void AddScene(Entitas.Data.SceneConfig newConfig, Entitas.Data.SceneInstanceInfo newScriptInstance) {
        var index = GameComponentsLookup.Scene;
        var component = CreateComponent<Entitas.Data.SceneComponent>(index);
        component.Config = newConfig;
        component.ScriptInstance = newScriptInstance;
        AddComponent(index, component);
    }

    public void ReplaceScene(Entitas.Data.SceneConfig newConfig, Entitas.Data.SceneInstanceInfo newScriptInstance) {
        var index = GameComponentsLookup.Scene;
        var component = CreateComponent<Entitas.Data.SceneComponent>(index);
        component.Config = newConfig;
        component.ScriptInstance = newScriptInstance;
        ReplaceComponent(index, component);
    }

    public void RemoveScene() {
        RemoveComponent(GameComponentsLookup.Scene);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.SkillComponent skill { get { return (Entitas.Data.SkillComponent)GetComponent(GameComponentsLookup.Skill); } }
    public bool hasSkill { get { return HasComponent(GameComponentsLookup.Skill); } }

    public void AddSkill(Entitas.Data.SkillInstanceInfo newInstance, Entitas.Data.StartSkillParam newStartParam) {
        var index = GameComponentsLookup.Skill;
        var component = CreateComponent<Entitas.Data.SkillComponent>(index);
        component.Instance = newInstance;
        component.StartParam = newStartParam;
        AddComponent(index, component);
    }

    public void ReplaceSkill(Entitas.Data.SkillInstanceInfo newInstance, Entitas.Data.StartSkillParam newStartParam) {
        var index = GameComponentsLookup.Skill;
        var component = CreateComponent<Entitas.Data.SkillComponent>(index);
        component.Instance = newInstance;
        component.StartParam = newStartParam;
        ReplaceComponent(index, component);
    }

    public void RemoveSkill() {
        RemoveComponent(GameComponentsLookup.Skill);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Entitas.Data.BuffComponent buff { get { return (Entitas.Data.BuffComponent)GetComponent(GameComponentsLookup.Buff); } }
    public bool hasBuff { get { return HasComponent(GameComponentsLookup.Buff); } }

    public void AddBuff(System.Collections.Generic.List<Entitas.Data.BuffInstanceInfo> newInstanceInfos) {
        var index = GameComponentsLookup.Buff;
        var component = CreateComponent<Entitas.Data.BuffComponent>(index);
        component.InstanceInfos = newInstanceInfos;
        AddComponent(index, component);
    }

    public void ReplaceBuff(System.Collections.Generic.List<Entitas.Data.BuffInstanceInfo> newInstanceInfos) {
        var index = GameComponentsLookup.Buff;
        var component = CreateComponent<Entitas.Data.BuffComponent>(index);
        component.InstanceInfos = newInstanceInfos;
        ReplaceComponent(index, component);
    }

    public void RemoveBuff() {
        RemoveComponent(GameComponentsLookup.Buff);
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherMovement;

    public static Entitas.IMatcher<GameEntity> Movement {
        get {
            if (_matcherMovement == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Movement);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherMovement = matcher;
            }

            return _matcherMovement;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherPosition;

    public static Entitas.IMatcher<GameEntity> Position {
        get {
            if (_matcherPosition == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Position);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherPosition = matcher;
            }

            return _matcherPosition;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherRotation;

    public static Entitas.IMatcher<GameEntity> Rotation {
        get {
            if (_matcherRotation == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Rotation);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherRotation = matcher;
            }

            return _matcherRotation;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherAnimation;

    public static Entitas.IMatcher<GameEntity> Animation {
        get {
            if (_matcherAnimation == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Animation);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherAnimation = matcher;
            }

            return _matcherAnimation;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherDisableMoveControl;

    public static Entitas.IMatcher<GameEntity> DisableMoveControl {
        get {
            if (_matcherDisableMoveControl == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.DisableMoveControl);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherDisableMoveControl = matcher;
            }

            return _matcherDisableMoveControl;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherDisableRotationControl;

    public static Entitas.IMatcher<GameEntity> DisableRotationControl {
        get {
            if (_matcherDisableRotationControl == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.DisableRotationControl);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherDisableRotationControl = matcher;
            }

            return _matcherDisableRotationControl;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherId;

    public static Entitas.IMatcher<GameEntity> Id {
        get {
            if (_matcherId == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Id);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherId = matcher;
            }

            return _matcherId;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherResource;

    public static Entitas.IMatcher<GameEntity> Resource {
        get {
            if (_matcherResource == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Resource);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherResource = matcher;
            }

            return _matcherResource;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherAI;

    public static Entitas.IMatcher<GameEntity> AI {
        get {
            if (_matcherAI == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.AI);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherAI = matcher;
            }

            return _matcherAI;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherPhysics;

    public static Entitas.IMatcher<GameEntity> Physics {
        get {
            if (_matcherPhysics == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Physics);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherPhysics = matcher;
            }

            return _matcherPhysics;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherCamp;

    public static Entitas.IMatcher<GameEntity> Camp {
        get {
            if (_matcherCamp == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Camp);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherCamp = matcher;
            }

            return _matcherCamp;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherDestory;

    public static Entitas.IMatcher<GameEntity> Destory {
        get {
            if (_matcherDestory == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Destory);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherDestory = matcher;
            }

            return _matcherDestory;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherAttr;

    public static Entitas.IMatcher<GameEntity> Attr {
        get {
            if (_matcherAttr == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Attr);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherAttr = matcher;
            }

            return _matcherAttr;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherBuffAttrChanged;

    public static Entitas.IMatcher<GameEntity> BuffAttrChanged {
        get {
            if (_matcherBuffAttrChanged == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.BuffAttrChanged);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherBuffAttrChanged = matcher;
            }

            return _matcherBuffAttrChanged;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherHp;

    public static Entitas.IMatcher<GameEntity> Hp {
        get {
            if (_matcherHp == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Hp);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherHp = matcher;
            }

            return _matcherHp;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherDead;

    public static Entitas.IMatcher<GameEntity> Dead {
        get {
            if (_matcherDead == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Dead);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherDead = matcher;
            }

            return _matcherDead;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherBorn;

    public static Entitas.IMatcher<GameEntity> Born {
        get {
            if (_matcherBorn == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Born);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherBorn = matcher;
            }

            return _matcherBorn;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherMainPlayer;

    public static Entitas.IMatcher<GameEntity> MainPlayer {
        get {
            if (_matcherMainPlayer == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.MainPlayer);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherMainPlayer = matcher;
            }

            return _matcherMainPlayer;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherTimeInfo;

    public static Entitas.IMatcher<GameEntity> TimeInfo {
        get {
            if (_matcherTimeInfo == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.TimeInfo);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherTimeInfo = matcher;
            }

            return _matcherTimeInfo;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherScene;

    public static Entitas.IMatcher<GameEntity> Scene {
        get {
            if (_matcherScene == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Scene);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherScene = matcher;
            }

            return _matcherScene;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherSkill;

    public static Entitas.IMatcher<GameEntity> Skill {
        get {
            if (_matcherSkill == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Skill);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherSkill = matcher;
            }

            return _matcherSkill;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherBuff;

    public static Entitas.IMatcher<GameEntity> Buff {
        get {
            if (_matcherBuff == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Buff);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherBuff = matcher;
            }

            return _matcherBuff;
        }
    }
}
