//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentsLookupGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class GameComponentsLookup {

    public const int AI = 0;
    public const int Animation = 1;
    public const int Buff = 2;
    public const int Destory = 3;
    public const int Id = 4;
    public const int Input = 5;
    public const int MainPlayer = 6;
    public const int Movement = 7;
    public const int Physics = 8;
    public const int Position = 9;
    public const int Resource = 10;
    public const int Rotation = 11;
    public const int Scene = 12;
    public const int Skill = 13;
    public const int Spatial = 14;
    public const int TimeInfo = 15;

    public const int TotalComponents = 16;

    public static readonly string[] componentNames = {
        "AI",
        "Animation",
        "Buff",
        "Destory",
        "Id",
        "Input",
        "MainPlayer",
        "Movement",
        "Physics",
        "Position",
        "Resource",
        "Rotation",
        "Scene",
        "Skill",
        "Spatial",
        "TimeInfo"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(Entitas.Data.AIComponent),
        typeof(Entitas.Data.AnimationComponent),
        typeof(Entitas.Data.BuffComponent),
        typeof(Entitas.Data.DestoryComponent),
        typeof(Entitas.Data.IdComponent),
        typeof(Entitas.Data.InputComponent),
        typeof(Entitas.Data.MainPlayerComponent),
        typeof(Entitas.Data.MovementComponent),
        typeof(Entitas.Data.PhysicsComponent),
        typeof(Entitas.Data.PositionComponent),
        typeof(Entitas.Data.ResourceComponent),
        typeof(Entitas.Data.RotationComponent),
        typeof(Entitas.Data.SceneComponent),
        typeof(Entitas.Data.SkillComponent),
        typeof(Entitas.Data.SpatialComponent),
        typeof(Entitas.Data.TimeInfoComponent)
    };
}
